### ISSUE TITLE
Unnecessary BOND_MAP environment variable

### ISSUE THREAD

**Issue by fleupold** [cowdao-grants/mb-billing#24]
https://github.com/cowdao-grants/mb-billing/blob/f997e6dafbe41b3f56559e405df6b6f0e2ec36b9/src/dune.ts#L47

We are already defining a payment query in the environment. Can we expect that query to specify the fine/draft target in one of its columns instead of defining another mapping here?

This would simplify the setup.

**Comment by cowanator** [comment]
The payment query is just a query ID. The BOND Map is meant to be a query parameter. We can hard-code this mapping in the query we want, but the more correct approach is to use parameters for this (in case it changes). Note that the other queries are currently hard coding this mapping:

Line 107 of https://dune.com/queries/3630322
which relies on this: https://dune.com/queries/3665113


Anyway, if we want to go that route we would need to adjust the `PAYMENT_QUERY`: https://dune.com/queries/3742749

Notice that the payment query was written and supplied by my account, while the others were provided. 

Please let me know how you would like to approach this.

**Comment by fleupold** [comment]
I think we should move it into the query (so that it's co-located with the other logic). Ideally the query is also checked into this repository and automatically synced as part of the CD pipeline (but even without that, having all query related parts in one place is better imo)
