### ISSUE TITLE
Provide example query id for PAYMENT_QUERY

### ISSUE THREAD

**Issue by fleupold** [cowdao-grants/mb-billing#25]
https://github.com/cowdao-grants/mb-billing/blob/f997e6dafbe41b3f56559e405df6b6f0e2ec36b9/README.md?plain=1#L70

As for the other crucial queries that are part of this repository.

**Comment by cowanator** [comment]
This is supplied in the sample ENV: 

https://dune.com/queries/3742749

**Comment by fleupold** [comment]
You are providing the other values as default parameters in the readme right there (and also `BILLING_QUERY` is provided in the README env section for another script). Let's be consistent.
